### ISSUE TITLE
It can not compile

### ISSUE THREAD

**Issue by Ravens62** [Shauren/WSTC#1]
1>------ Build started: Project: version.h, Configuration: Debug Win32 ------
2>------ Build started: Project: Shared, Configuration: Debug Win32 ------
1>Generating sniffer version strings
1>fatal: No names found, cannot describe anything.
2>Replacement.c
2>RemoteModule.c
2>Output.c
2>Generating Code...
2>Shared.vcxproj -> D:\Hry\On-Line\World of Warcraft\WSTC-master\bin\Debug\Shared.lib
3>------ Build started: Project: WSTC, Configuration: Debug Win32 ------
4>------ Build started: Project: Injecter, Configuration: Debug Win32 ------
4>Assembling ..\src\Injecter\Hooks_x64.asm...
4>Assembling ..\src\Injecter\Hooks_x86.asm...
3>Systém nemůže nalézt uvedenou cestu.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "setlocal
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: cd ..\src\CodeBreaker
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: copy /b Rebuilder.cl+,, >nul
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: endlocal
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code 1.
3>Done building project "WSTC.vcxproj" -- FAILED.
4>InjectedData.c
4>Injecter.c
4>Generating Code...
4>   Creating library D:\Hry\On-Line\World of Warcraft\WSTC-master\bin\Debug\Injecter.lib and object D:\Hry\On-Line\World of Warcraft\WSTC-master\bin\Debug\Injecter.exp
4>Injecter.vcxproj -> D:\Hry\On-Line\World of Warcraft\WSTC-master\bin\Debug\Injecter.dll
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Shauren** [comment]
fixed in 5ae40730f6e2139c7782848f81e650881ad7a63c

**Comment by Shauren** [comment]
Also judging by your directory name "WSTC-master" you downloaded zip from github instead of doing git clone. Build requires to be done in a git repository to generate version string, just like TrinityCore
