### ISSUE TITLE
It can not compile

### ISSUE THREAD

**Issue by Ravens62** [Shauren/WSTC#2]
And there's no difference in downloading a zip or clone from git

Error	C2087	'StringData': missing subscript	WSTC	C:\Users\pavel\Documents\WSTC\src\WSTC\Strings.c	4	
Error	C1083	Cannot open include file: 'MemoryModule.h': No such file or directory	WSTC	C:\Users\pavel\Documents\WSTC\src\WSTC\DynamicLibrary.c	3	
Error	C2065	'MAX_ENCODED_STRING_LEN': undeclared identifier	WSTC	C:\Users\pavel\Documents\WSTC\src\WSTC\Strings.c	4	
Error	C2057	expected constant expression	WSTC	C:\Users\pavel\Documents\WSTC\src\WSTC\Strings.c	4	
Error	C2466	cannot allocate an array of constant size 0	WSTC	C:\Users\pavel\Documents\WSTC\src\WSTC\Strings.c	4

**Comment by Shauren** [comment]
e784a88ad1eb7ff07e92406ec089288ad9eaf8f1
