### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Abd-ulRahman** [Shauren/WSTC#3]
Good Day
Dear Shauren
I am trying to get WSTC_9.0.2.37474.pkt
Please if you don't mind to guide me where to get
Thanks in Advance
Best Regards

**Comment by Shauren** [comment]
There isnt one, WSTC was discontinued with the release of patch 7.3.0

**Comment by Abd-ulRahman** [comment]
Thanks

**Comment by Abd-ulRahman** [comment]
I did find the following sniffer
on the other hand I do not know how to use it
Would you please help me?
https://github.com/Abd-ulRahman/snf-9.0.2.37474vs9.0.5.37864/tree/5a835c88e00cff59b4cf4441948b63b0c2e3f903
As I compiled it and used the 5 available net Work adapter including Realtek Ethernet but it does not sniff.
Thanks in advance.
Best Regards.

**Comment by Abd-ulRahman** [comment]
For your kind information I'm using localhost shadowcore repack

**Comment by Shauren** [comment]
Why would I ever help anyone with a project that is not mine?

**Comment by Abd-ulRahman** [comment]
I did ask you cause your expert enough as you have worked in the same field, semi like project ……Sorry for asking.
